### ISSUE TITLE
When reading configuration, default values should be set before bailing out

### ISSUE THREAD

**Issue by ladislav-zezula** [kevoreilly/capemon#15]
The [read_config](https://github.com/kevoreilly/capemon/blob/21ac0e0a6e809e6657368796e5c8c776059e3722/config.c#L956) function bails out without setting default values, when the config file doesn't exist at all.

Use case: For simple capemon debugging, where i just run `loader_x64.exe load c:\test\capemon_x64_dbg.dll sample.exe` when having kernel debugger on.

Problem: Default value of `g_config.hook_type` is 0, which is `HOOK_HOTPATCH_JMP_INDIRECT`. In x64, it causes total havoc in the hooked functions.

**Comment by kevoreilly** [comment]
Thank you for this input. I am definitely keen to try and prevent exceptions when no config file is found - however your PR ignores the standalone use case which is intended for exactly the scenario you describe...

I too work with standalone monitor mostly for debugger/tracer testing, Therefore capemon checks to see if there is also a config.ini in the same path. This is so anyone can easily test options with a simple ini file next to capemon.

A typical config.ini for testing might contain for example:

standalone=1
procdump=0
caller-dump=0
yarascan=0
bp0=ep

The standalone option is also designed for use outside the sandbox, so the api hook output is written to file instead of pipe, and debug output is instead sent to DebugView. This means standalone capemon needs 3 files: loader, config and monitor, So try creating a config.ini and consider this as an alternative to looking for the config inside the sandbox.

**Comment by kevoreilly** [comment]
Since you are into debugging please do give the standalone debugger a try!
